### ISSUE TITLE
[1.14.4] Error processing version information for version check

### ISSUE THREAD

**Issue by noobanidus** [Lothrazar/ElementaryOres#4]
```
[16:23:14] [Forge Version Check/INFO]: [elementaryores] Starting version check at https://raw.githubusercontent.com/Lothrazar/elementary-ores/master/update.json
[16:23:14] [Forge Version Check/WARN]: Failed to process update information
java.lang.NullPointerException: null
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:216) [?:?]
	at net.minecraftforge.fml.VersionChecker$1$$Lambda$7463/1790320125.accept(Unknown Source) [?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_51]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?]
```

Going to this URL, it appears to not exist currently or be blank.

**Comment by Lothrazar** [comment]
1.15 is  abandoned by all the mod devs and pack makers. fixed in 1.16 https://www.curseforge.com/minecraft/mc-mods/elementary-ores/files/3390855
